### PR TITLE
loader: add 'override any app' feature

### PR DESCRIPTION
**Pull request by natinusala**
This allows overriding any app with HBL by using `hbl_tid=app` in `loader.ini`. Useful with `override_key=R`, to run HBL on top of any game just by pressing R when launching it.

### CODE REVIEW

**Comment by CTCaer** [comment]
"unused" buttons or combos, seem more normal to me.
E.g. L3 or R3 (stick buttons)

**Comment by SciresM** [comment]
@CTCaer eh, it seems a bit odd to make a user have to hold down a stick button. Plus stuff should be user-configurable.

**Comment by natinusala** [comment]
Is it good enough to compare the tid with `0100000000010000` ?

**Comment by CTCaer** [comment]
I don't follow why it's odd. The stick is zero finicky and it's used since ancient times with PS2 easter eggs.

True that it should be configurable (although almost no one changes this).
The only problem is that >= 0100000000010000 will not always work for the better.

**Comment by natinusala** [comment]
I changed `*` with `app` and added a title id filter, it needs to be `>= 0100000000010000` to be overriden.

**Comment by misson20000** [comment]
TID filtering seems to be a bit of a hack. Any reason you can't just check the application bit?

**Comment by natinusala** [comment]
I didn't find any documentation on the title id format so I didn't know there was such a bit. 

Which bit is it ? I can submit another PR to improve the filter.

**Comment by misson20000** [comment]
Not in the TID, but in the process's flags from NPDM

**Comment by SciresM** [comment]
@misson20000 I accepted it on two grounds:

1. fs.mitm must also be able to filter on any condition we use, and fs.mitm does not have access to NPDM flags or metadata.

2. The official application TID range is `0x0100000000010000`-`0x01FFFFFFFFFFFFFF`, per game NPDMs. Anything outside of that range is not an official application, and so we don't necessarily need to care about it.

**Comment by misson20000** [comment]
Alright, that makes sense.

**Pull request merged**
