### PR TITLE
Uncomment fatal_auto_reboot_interval and set to 0

### PR DESCRIPTION
**Pull request by SunTheCourier**
* Would work better for homebrew apps such as Kosmos Toolbox

### CODE REVIEW

**Comment by HookedBehemoth** [comment]
Then they should do it themself in their release.
The fatal screen is there for something and should not be ignored by default.

**Comment by cole-h** [comment]
Setting it to 0 functions the same as having it commented. My opinion doesn't count for much, but I don't think this change is controversial. 

https://github.com/Atmosphere-NX/Atmosphere/blob/153e97a80faf8f92aa80dcc10d09a3c0eb50243e/stratosphere/fatal/source/fatal_config.cpp#L88

**Comment by HookedBehemoth** [comment]
Sorry, I overlooked that part.

**Comment by SunTheCourier** [comment]
As i said it's so homebrew like Kosmos Toolbox can modify the value properly

**Comment by SciresM** [comment]
I'll do this when I add ro!ease_nro_restriction default. Not relevant until next release anyway.

**Pull request closed without merging**
