### PR TITLE
Allow for untracked config.h

### PR DESCRIPTION
**Pull request by Qyriad**
`#include "src/config.h"` if it exists in fusée primary

### CODE REVIEW

**Comment by kitlith** [comment]
couldn't this also be accomplished with gcc's `-include` command line argument? e.g. conditionally add `-include src/config.h` instead of `-DHAS_CONFIG_H`?

**Comment by jowadmax** [comment]
@kitlith yes, but then you force the file to be included with every compiled unit (.c file). The way it's done in this PR makes it so that you can selectively include it in files of your choosing (exclusively) if it the config file happens to exist.

**Comment by kitlith** [comment]
fair enough.

**Comment by Qyriad** [comment]
Due to recent events regarding the ReSwitched team, I no longer desire to support Atmosphère.

**Pull request closed without merging**
