### PR TITLE
Allow multiple override keys

### PR DESCRIPTION
**Pull request by piepie62**
This was tested by copying the changes over to before all dmnt commits. I can confirm that it works when tested in that way.

### CODE REVIEW

**Comment by SciresM** [comment]
Not sure this syntax is desirable -- also, not sure that we prefer an OR of keys rather than an AND....

Needs thought.

**Comment by piepie62** [comment]
Don't quite see how an AND would work, to be quite honest

**Comment by SciresM** [comment]
@piepie62 "require L+R" vs "require L or R", since you're currently doing an OR.

**Comment by piepie62** [comment]
Oh, I thought you meant in the setting code. Yeah, that's a totally valid option, and I could do it pretty easily, if you want

**Comment by SciresM** [comment]
@piepie62 syntax is important -- again, needs thought. Also PR would need to fix in fs.mitm, too, and not just loader.

**Comment by piepie62** [comment]
I thought about doing that, but because it's a fairly minor edit, I decided to PR what I had and get your opinion on it

**Comment by piepie62** [comment]
Oops, sorry, I didn't realize that fs.mitm used the same code. I'll fix that now.

**Comment by piepie62** [comment]
What do you mean by "syntax is important", by the way? If I had more information I might be able to address that issue

**Comment by piepie62** [comment]
Closing this because I don't really have any interest in it anymore. Don't really see a use case in the foreseeable future, and I only really started it originally because I figured it would be possible.

**Pull request closed without merging**
