### PR TITLE
Add baseline support for 14.0.0 

### PR DESCRIPTION
**Pull request by SciresM**
This adds basic support for 14.0.0, bumps version to 1.3.0. I guess I need to write a changelog for that.

Mesosphere/erpt/fatal/pm are reverse engineered/updated, fusee/exosphere as well.

Loader/Boot to come post-first-release.

### CODE REVIEW

**Comment by Evilander** [comment]
Yeah, I reached out about a bitcoin wallet to help support your efforts. I accidentally updated (I know, I know) - so I hoped for a quick turn around. Thanks for the hard work!

**Comment by SciresM** [comment]
> Yeah, I reached out about a bitcoin wallet to help support your efforts. I accidentally updated (I know, I know) - so I hoped for a quick turn around. Thanks for the hard work!

I appreciate the thought, but I do not accept compensation of any kind for my work on Atmosphere. I do it strictly for free.

If you are in a particularly giving mood, my charity of choice is [the Electronic Frontier Foundation](https://www.eff.org/), and you're welcome to make a donation there in lieu of one to me.

**Comment by Evilander** [comment]
> > Yeah, I reached out about a bitcoin wallet to help support your efforts. I accidentally updated (I know, I know) - so I hoped for a quick turn around. Thanks for the hard work!
> 
> I appreciate the thought, but I do not accept compensation of any kind for my work on Atmosphere. I do it strictly for free.
> 
> If you are in a particularly giving mood, my charity of choice is [the Electronic Frontier Foundation](https://www.eff.org/), and you're welcome to make a donation there in lieu of one to me.

Cool. I will do that when I get off work today. No rush - but with the progress, are we looking at a release in the next day or two? I see a lot of progress, but can't make sense of it in the grand scheme of things.

**Comment by SciresM** [comment]
> > > Yeah, I reached out about a bitcoin wallet to help support your efforts. I accidentally updated (I know, I know) - so I hoped for a quick turn around. Thanks for the hard work!
> > 
> > 
> > I appreciate the thought, but I do not accept compensation of any kind for my work on Atmosphere. I do it strictly for free.
> > If you are in a particularly giving mood, my charity of choice is [the Electronic Frontier Foundation](https://www.eff.org/), and you're welcome to make a donation there in lieu of one to me.
> 
> Cool. I will do that when I get off work today. No rush - but with the progress, are we looking at a release in the next day or two? I see a lot of progress, but can't make sense of it in the grand scheme of things.

The pre-release is currently in public testing in ReSwitched's discord, if there aren't any issues found the pre-release will go up in about an hour.

**Pull request merged**
