### PR TITLE
Support for expanded NAND by roblâbla

### PR DESCRIPTION
**Pull request by rashevskyv**
Need for starting with extended NAND chip

### CODE REVIEW

**Comment by SciresM** [comment]
Does this break non-expanded NAND?

**Comment by rashevskyv** [comment]
No issues with both of my consoles. Works great with original 32Gb NAND chip

**Comment by CTCaer** [comment]
why hardcode it and not set it via EXT_CSD_SEC_CNT?

**Comment by rashevskyv** [comment]
> 
> 
> why hardcode it and not set it via EXT_CSD_SEC_CNT?

I do not skilled enough to do it myself, and it was hardcoded by default, but for 32Gb NAND. I had a problem with starting extended NAND on Atmosphere, roblâbla in Discord gave this quick fix for me.

**Comment by shchmue** [comment]
```diff
- model.num_sectors = (256ull << 30) / model.sector_size;
+ model.num_sectors = g_emmc_user_mmcpart.device->ext_csd.sectors;```

**Comment by shchmue** [comment]
oh. oops. the sdmmc code here doesn't init `sectors` for some reason so it'll need to be
`model.num_sectors = *(uint32_t*)g_emmc_user_mmcpart.device->ext_csd.raw_sectors[0];`
or do the math with all four bitshifted bytes in case i did that cast wrong 🤦‍♀️

**Comment by shchmue** [comment]
with a better understanding of the code path, i'll need to think more. fixing this would also probably fix
https://github.com/Atmosphere-NX/Atmosphere/blob/master/fusee/fusee-secondary/src/nxfs.c#L268

**Pull request closed without merging**
