### PR TITLE
Minor Road Map correction

### PR DESCRIPTION
**Pull request by JeffVi**

### CODE REVIEW

**Comment by SciresM** [comment]
Is this a troll?

It's a duplicate of #1379 at best.

**Comment by JeffVi** [comment]
That’s unfortunate

**Comment by SciresM** [comment]
Can I ask why you opened a duplicate of a PR that was closed with an explanation less than four hours ago?

**Comment by JeffVi** [comment]
Well, I didn’t noticed.
I’m sorry if you think that it is a troll.
Just an unlucky coincidence.

**Comment by SciresM** [comment]
Nah, it's perfectly plausible that it's a coincidence. Thank you for trying to help improve Atmosphere's docs, and have a nice rest of your day :)

**Pull request closed without merging**
