### PR TITLE
I fixed some hbl setting issues in rnx

### PR DESCRIPTION
**Pull request by sandhoners123**
I fixed some of my code a little. Please tell the places which are wrong instead of just closing it

### CODE REVIEW

**Comment by SciresM** [comment]
Duplicate of #551.

**Comment by sandhoners123** [comment]
But what is the problem with the code

**Comment by SciresM** [comment]
mostly the code

**Comment by sandhoners123** [comment]
What is the problem with it. Which line

**Comment by SciresM** [comment]
all of them

**Comment by sandhoners123** [comment]
What needs to be changed

**Comment by SciresM** [comment]
it's fundamentally not mergable.

**Comment by sandhoners123** [comment]
But what parts of the code needs to be changed

**Comment by jakibaki** [comment]
The problem is the whole idea. It's not desirable for atmosphere to pretend to be a specific atmosphere fork.

**Comment by sandhoners123** [comment]
I guess I will make my own fork of atmosphere then

**Comment by SciresM** [comment]
lol

**Pull request closed without merging**
