### PR TITLE
ncm: update to 10.0.0

### PR DESCRIPTION
**Pull request by Adubbz**
As per title.

### CODE REVIEW

**Comment by Djowietje** [comment]
Wow, you were fast. Let's hope it get's reviewed/merged soon :)

**Comment by oceanmaster41** [comment]
Pls release soon. I updated to 10.0.0 accidently:)

**Comment by joaomarques11** [comment]
Love the work you guys doing. Thanks soo soo much. Hopefully waiting the 10.0 version cuz I f.king updated cus im a dumb biitc

**Comment by CalenitoXD** [comment]
Where can i get the latest 10.0.0 update on atmosphere?

**Comment by ReignOfComputer** [comment]
> Where can i get the latest 10.0.0 update on atmosphere?

June 15

**Pull request merged**
