### PR TITLE
Add arguments support to Daybreak

### PR DESCRIPTION
**Pull request by HamletDuFromage**
Just a small change to be able to launch daybreak with a specified update path

### CODE REVIEW

**Comment by SciresM** [comment]
I don't understand -- hbmenu doesn't actually support arguments to daybreak like this?

Closing in the absence of an understanding why this is justified/desirable.

**Comment by HamletDuFromage** [comment]
Well it'd be mostly for [envSetNextLoad()](https://switchbrew.github.io/libnx/env_8h.html#ab3fa9a2b9c3296e182c7caf618dbb4e0), though it also works with nxlink. Opening daybreak on the right folder from the get-go would be justifiable for this use case, and changes nothing for regular use

**Comment by HamletDuFromage** [comment]
So, no chance of merging right?

**Comment by SciresM** [comment]
I've given it some thought, and would accept a version of this modulo caveats, I think. Reach out to me on discord to discuss?

**Pull request closed without merging**
