### PR TITLE
fusee: fix typos in NCM's content header

### PR DESCRIPTION
**Pull request by friedkeenan**

### CODE REVIEW

**Comment by SciresM** [comment]
What? That wasn't a typo.

**Comment by SciresM** [comment]
Well, spl is a typo I guess. But NCM is intentional.

**Comment by friedkeenan** [comment]
All the other names are lowercase though?

**Comment by SciresM** [comment]
That's correct.

**Comment by friedkeenan** [comment]
Okie dokie then

**Pull request closed without merging**
