### PR TITLE
Implement support for emummc.

### PR DESCRIPTION
**Pull request by SciresM**
Note: there are still a couple of commits yet to be pushed, but I'm making this PR now for reasons.

Also note: there may be a commit or two that don't make it in six days before the solstice due to time constraints. But that (and squashing bugs) is what 0.9.1 is for, amirite?

Thanks @m4xw and @CTCaer for collaborating :)

### CODE REVIEW

**Comment by SciresM** [comment]
Merge + release currently expected near end-of-day pacific time.

**Comment by UnicornsOnLSD** [comment]
Happy June 15th!

**Comment by joelc608** [comment]
Amazing work! I would like to thank all the devs for their hard work on emummc :) Happy June 15th!

**Comment by adryyyy** [comment]
i will try this now

**Comment by UnicornsOnLSD** [comment]
Is there a difference between EmuMMC and EmuNAND?

**Comment by TheRealAman** [comment]
> Is there a difference between EmuMMC and EmuNAND?

im pretty sure emummc is just what they're calling it

**Comment by fennectech** [comment]
Thank you for all the hard work thats gone into this.  And a release on such a holy day    All i can say is thank you :)

**Pull request merged**
