### PR TITLE
Add component overview to the readme

### PR DESCRIPTION
**Pull request by neobrain**
Loosely based on https://github.com/Atmosphere-NX/Atmosphere/projects - such an overview was really needed, and now the information is in the place where people will actually find it :)

### CODE REVIEW

**Comment by SciresM** [comment]
This is a really good thing to add, thanks. The *dumbest* request -- could you invert the order of the component listing? Once that's done will merge.

**Comment by neobrain** [comment]
Sure, will do in a bit!

**Comment by jowadmax** [comment]
It would also be nice if this new section followed the formatting (bold for name of component, indentation, etc) of the Credits section. Not super critical but makes the frontpage look more consistent :)

Thanks for the effort.

**Comment by neobrain** [comment]
Changed the component order by request of @SciresM.

@jowadmax I like the current formatting a bit better, but do feel free to submit a followup PR if you like after this gets merged.

**Pull request merged**
