### PR TITLE
Implement rnx and rnx_mitm stub in ams

### PR DESCRIPTION
**Pull request by sandhoners123**
Not yet fully good looking or complete. May crash. Thinking of removing rnx_mitm as ams does the same thing

### CODE REVIEW

**Comment by sandhoners123** [comment]
Alright am removing the rnx_mitm service as it is a waste of sysmodules

**Comment by SciresM** [comment]
no

**Comment by sandhoners123** [comment]
Why? Is the ide a problem or is the code bad

**Comment by SciresM** [comment]
yes

**Comment by sandhoners123** [comment]
So what needs to change in the code

**Comment by EliseZeroTwo** [comment]
lol

**Comment by sandhoners123** [comment]
I fixed the code partially

**Comment by StevenMattera** [comment]
Modifying Atmosphere is not needed to get DeltaLaunch to run. You can find the service separately here: https://github.com/StevenMattera/ReiNX-Spoofer Please stop creating issues and PRs with Atmosphere.

**Pull request closed without merging**
